server:
  port: 8080

spring:
  application:
    name: AirlinersDailyBot

  datasource:
    url: jdbc:postgresql://${DB_SERVER_IP}:5433/airliners-bot
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver

  jpa:
    properties.hibernate:
      globally_quoted_identifiers: true
      show_sql: false
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:db/liquibase-master.yml

  kafka:
    bootstrap-servers: ${KAFKA_SERVER_IP}:9092
    top-pictures-topic-name: airliners-top-sending
    group-id: airliners-bot-app-group
    auto-offset-reset: earliest
    core-pool-size: 3
    max-pool-size: 3
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

bot:
  name: AirlinersDailyBot
  token: ${BOT_TOKEN}

client:
  baseUrl: https://www.airliners.net
  maxBufferSize: 1024000
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 YaBrowser/24.7.0.0 Safari/537.36

app:
  defaultLangCode: ru
  picture:
    update:
      initialDelay: 1000
      fixedDelay: 180000

resilience4j:
  ratelimiter:
    instances:
      subscrSendingLimiter:
        limit-for-period: 10
        limit-refresh-period: 1s
        timeout-duration: 10s

logging:
  level:
    root: info
    com.github.svyaz: info
    org.telegram: info
