server:
  port: 8081

spring:
  application:
    name: AirlinersDaily-Test-Bot

  datasource:
    url: jdbc:postgresql://localhost:5433/airliners-bot
    username: app
    password: app
    driverClassName: org.postgresql.Driver
    hikari:
      pool-name: HikariCP
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      minimum-idle: 5
      maximum-pool-size: 10

  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate:
      globally_quoted_identifiers: true
#      hbm2ddl.auto: update
      show_sql: true
    hibernate:
#      ddl-auto: update

  liquibase:
    enabled: true
    change-log: classpath:db/liquibase-master.yml

  kafka:
    bootstrap-servers: localhost:9092
    top-pictures-topic-name: airliners-top-sending
    group-id: airliners-bot-app-group
    auto-offset-reset: earliest
    core-pool-size: 3
    max-pool-size: 3
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      auto-offset-reset: earliest
      max-poll-interval-ms: 30000
      heartbeat-interval-ms: 3000
      session-timeout-ms: 10000

  cache:
    type: caffeine
    caffeine.spec: maximumSize=50,expireAfterWrite=360m

bot:
  name: AirlinersDaily-Test-Bot
  token: ${BOT_TOKEN}

client:
  baseUrl: https://www.airliners.net
  maxBufferSize: 1024000
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 YaBrowser/24.7.0.0 Safari/537.36
  maxConnections: 100
  pendingAcquireTimeout: 10000
  maxIdleTime: 5000
  pendingAcquireMaxCount: -1

translation-client:
  baseUrl: https://translate.api.cloud.yandex.net
  maxBufferSize: 256000
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 YaBrowser/24.7.0.0 Safari/537.36
  maxConnections: 20
  pendingAcquireTimeout: 10000
  maxIdleTime: 5000
  pendingAcquireMaxCount: -1
  apiKey: ${YA_TRANSLATE_API_KEY}

app:
  defaultLangCode: en
  translations: [ru, fr]
  picture:
    update:
      initialDelay: 1000
      fixedDelay: 180000

#resilience4j:
#  ratelimiter:
#    instances:
#      subscrSendingLimiter:
#        limit-for-period: 1
#        limit-refresh-period: 1s
#        timeout-duration: 10s

ratelimiter:
  properties:
    subscrSendingLimiter:
      callsNumber: 3
      periodMillis: 1000

logging:
  level:
    root: info
    com.github.svyaz: debug
    org.telegram: info
#    com.zaxxer.hikari: debug
#    org.springframework.cache: info
#    org.springframework.web: trace
