version: '3.9'
services:
  app:
    image: airliners-bot-app-1
    restart: always
  postgres:
    image: postgres:14.8-alpine3.18
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: 'airliners-bot'
      POSTGRES_USER: 'app'
      POSTGRES_PASSWORD: 'app'
    ports:
      - '5433:5432'
  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
    ports:
      - '2181:2181'
  kafka:
    image: wurstmeister/kafka
    restart: always
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 109.73.207.27
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "airliners-top-sending:1:3"
    depends_on:
      - zookeeper
  libretranslate:
    image: libretranslate/libretranslate
    container_name: libretranslate
    restart: always
    ports:
      - "5000:5000"
    command: --load-only ru,en,fr
    environment:
      - LT_UPDATE_MODELS=false
