version: "3.9"
services:
  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "airliners-bot"
      POSTGRES_USER: "app"
      POSTGRES_PASSWORD: "app"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "airliners-top-sending:1:3"
    depends_on:
      - zookeeper
