server:
  port: 8081

spring:
  application:
    name: AirlinersDaily-Test-Bot
  r2dbc:
    url: r2dbc:h2:mem:///~/db/airliners-bot-db
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

bot:
  name: AirlinersDaily-Test-Bot
  token: ${BOT_TOKEN}

client:
  baseUrl: https://www.airliners.net
  maxBufferSize: 1024000
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 YaBrowser/24.7.0.0 Safari/537.36

app:
  defaultLangCode: ru

logging.level.root: info
logging.level.com.github.svyaz: debug
logging.level.org.telegram: trace
#logging.level.org.springframework.web: trace
